name: Lint

on: [push]

jobs:
  phpcs-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install Composer Dependencies
          uses: php-actions/composer@v6
          with:
            php_version: 7.3
            args: --no-progress --prefer-dist --optimize-autoloader
        - name: PHP Lint
          run: "composer run lint"

  js-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2.4.1
          with:
            node-version: '16.x'

        - name: Install Dependencies
          run: npm ci

        - name: Run ESLint
          run: npm run lint

        - name: Run i18 Validation
          run: npm run i18n:validate
